language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
  # PyPy versions
#  - "pypy"   # currently Python 2.7.13, PyPy 7.1.1
#  - "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0
# command to install dependencies
install:
  - pip install -r requirements.txt
#  - pip install .
# command to run tests
script: pytest tests/

language: python
python:
  - "3.6"

install: "pip install -r requirements.txt"

script:
  - pytest --cov=./

after_success:
  - codecov